services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: app
      POSTGRES_DB: messenger
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
